[book]
authors = ["ruohao"]
language = "en"
src = "src"
title = "Ruohao's Cyber Notes & Writeups"

[build]
build-dir = "docs"

[output.html.fold]
enable = true

[preprocessor.tagger]
command = "mdbook-tagger"

# [preprocessor.wikilinks]
# command = "scripts/wikilinks.sh"
